### ISSUE TITLE
 Fatal Exception: java.lang.IllegalStateException Couldn't read row 787, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by yassinsameh** [QuisApp/flutter_contacts#175]
Similarly to issue #86 and #44. The issue is on Android, has been there for a long time, unable to debug further logs from production. @joachim-quis. 

```Fatal Exception: java.lang.IllegalStateException
Couldn't read row 787, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
android.database.CursorWindow.nativeGetString (CursorWindow.java)
android.database.CursorWindow.getString (CursorWindow.java:469)
android.database.AbstractWindowedCursor.getString (AbstractWindowedCursor.java:53)
android.database.CursorWrapper.getString (CursorWrapper.java:141)
co.quis.flutter_contacts.FlutterContacts$Companion.select$getString (FlutterContacts.java:4)
co.quis.flutter_contacts.FlutterContacts$Companion.select (FlutterContacts.java:325)
co.quis.flutter_contacts.FlutterContacts$Companion.select$default (FlutterContacts.java:27)
co.quis.flutter_contacts.FlutterContactsPlugin$onMethodCall$2.invokeSuspend (FlutterContactsPlugin.java:154)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:11)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.java:134)
kotlinx.coroutines.internal.LimitedDispatcher$Worker.run (LimitedDispatcher.java:3)
kotlinx.coroutines.scheduling.TaskImpl.run (TaskImpl.java:2)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.java:14)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.java:28)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.java)```

**Comment by scaleit-lt** [comment]
We are experiencing the same issue. Here is the stack trace we get:

Android 6.0.1

java.lang.IllegalStateException: Couldn't read row 867, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetString(CursorWindow.java)
    at android.database.CursorWindow.getString(CursorWindow.java:438)
    at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
    at android.database.CursorWrapper.getString(CursorWrapper.java:137)
    at m1.c$a.S(FlutterContacts.kt:5)
    at m1.c$a.O(FlutterContacts.kt:25)
    at m1.c$a.P(FlutterContacts.kt:1)
    at m1.d$g.n(FlutterContactsPlugin.kt:155)
    at h5.a.h(ContinuationImpl.kt:12)
    at z5.t0.run(DispatchedTask.kt:124)
    at e6.o$a.run(LimitedDispatcher.kt:4)
    at g6.k.run(Tasks.kt:3)
    at g6.a.M(CoroutineScheduler.kt:1)
    at g6.a$c.d(CoroutineScheduler.kt:15)
    at g6.a$c.p(CoroutineScheduler.kt:29)
    at g6.a$c.run(CoroutineScheduler.kt:1)

**Comment by joachim-quis** [comment]
Excited news, this is now fixed in [v2.0.0-beta.1](https://pub.dev/packages/flutter_contacts/versions/2.0.0-beta.1) 🎉

The Android implementation has completely rewritten cursor handling with proper bounds checking and null safety.
