### ISSUE TITLE
Java.lang.IllegalStateException: Module with the Main dispatcher is missing

### ISSUE THREAD

**Issue by bhavya-shiprocket** [QuisApp/flutter_contacts#181]
E/AndroidRuntime( 2571): java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'

`E/AndroidRuntime( 2571): 	at sb.b0.d(MainDispatchers.kt:81)
E/AndroidRuntime( 2571): 	at sb.c0.i0(MainDispatchers.kt:112)
E/AndroidRuntime( 2571): 	at sb.c0.d0(MainDispatchers.kt:96)
E/AndroidRuntime( 2571): 	at sb.m.b(DispatchedContinuation.kt:317)
E/AndroidRuntime( 2571): 	at tb.a.b(Cancellable.kt:30)
E/AndroidRuntime( 2571): 	at tb.a.d(Cancellable.kt:25)
E/AndroidRuntime( 2571): 	at nb.o0.l(CoroutineStart.kt:110)
E/AndroidRuntime( 2571): 	at nb.a.L0(AbstractCoroutine.kt:126)
E/AndroidRuntime( 2571): 	at nb.i.c(Builders.common.kt:56)
E/AndroidRuntime( 2571): 	at nb.g.c(Unknown Source:1)
E/AndroidRuntime( 2571): 	at nb.i.d(Builders.common.kt:47)
E/AndroidRuntime( 2571): 	at nb.g.d(Unknown Source:1)
E/AndroidRuntime( 2571): 	at s1.d.onRequestPermissionsResult(FlutterContactsPlugin.kt:127)
E/AndroidRuntime( 2571): 	at io.flutter.embedding.engine.c$c.j(FlutterEngineConnectionRegistry.java:779)
E/AndroidRuntime( 2571): 	at io.flutter.embedding.engine.c.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:411)
E/AndroidRuntime( 2571): 	at io.flutter.embedding.android.d.x(FlutterActivityAndFragmentDelegate.java:761)
E/AndroidRuntime( 2571): 	at io.flutter.embedding.android.h.n1(FlutterFragment.java:915)
E/AndroidRuntime( 2571): 	at io.flutter.embedding.android.i.onRequestPermissionsResult(FlutterFragmentActivity.java:549)
E/AndroidRuntime( 2571): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8618)
E/AndroidRuntime( 2571): 	at android.app.Activity.dispatchActivityResult(Activity.java:8475)
E/AndroidRuntime( 2571): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5509)
E/AndroidRuntime( 2571): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5555)
E/AndroidRuntime( 2571): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
E/AndroidRuntime( 2571): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 2571): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 2571): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 2571): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
E/AndroidRuntime( 2571): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2571): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime( 2571): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime( 2571): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime( 2571): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2571): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime( 2571): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime( 2571): 	Suppressed: sb.k: [m2{Cancelling}@162032b, Dispatchers.Main[missing]]`

**Comment by joachim-quis** [comment]
Hi! I just released [v2.0.0-beta.1](https://pub.dev/packages/flutter_contacts/versions/2.0.0-beta.1), a complete rewrite of this plugin with more robust implementation 🎉

The Android implementation has been completely rewritten with proper Kotlin coroutine handling.
