### ISSUE TITLE
BUG: crash after calling requestPermissions only on Android

### ISSUE THREAD

**Issue by rbarzel** [QuisApp/flutter_contacts#65]
Hi, I'm quite new to flutter so this might be operator error. I'm seeing the following error on Android when calling `FlutterContacts.requestPermission(readonly: true)`. No error on iOS.

```
D/CompatibilityChangeReporter(16037): Compat change id reported: 78294732; UID 10265; state: ENABLED
D/AndroidRuntime(16037): Shutting down VM
E/AndroidRuntime(16037): FATAL EXCEPTION: main
E/AndroidRuntime(16037): Process: com.mpom.flutt_mpom_3, PID: 16037
E/AndroidRuntime(16037): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.mpom.flutt_mpom_3/com.mpom.flutt_mpom_3.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime(16037): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
E/AndroidRuntime(16037): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
E/AndroidRuntime(16037): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(16037): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(16037): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(16037): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(16037): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
E/AndroidRuntime(16037): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16037): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(16037): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(16037): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(16037): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(16037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(16037): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.dexterous.flutterlocalnotifications.PermissionRequestListener.complete(boolean)' on a null object reference
E/AndroidRuntime(16037): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onRequestPermissionsResult(FlutterLocalNotificationsPlugin.java:1580)
E/AndroidRuntime(16037): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(16037): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(16037): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:757)
E/AndroidRuntime(16037): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(16037): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8759)
E/AndroidRuntime(16037): 	at android.app.Activity.dispatchActivityResult(Activity.java:8617)
E/AndroidRuntime(16037): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
E/AndroidRuntime(16037): 	... 13 more
```

**Env:**
```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-US)
    • Flutter version 3.3.0 on channel stable at /Users/ronbarzel/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ronbarzel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • Pixel 4 (mobile) • adb-99271FFAZ004KY-VJf9D2._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • Pixel 4 (mobile) • adb-9A231FFAZ002R1-gMwsRs._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos                                            • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)     • chrome                                           • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Thanks!

**Comment by rbarzel** [comment]
Update: I think this crash happens **only** when running in debug mode. Seems to work fine with a release apk.

**Comment by AlexeyRottCr** [comment]
I also encountered this problem.

**Comment by AlexeyRottCr** [comment]
I found a crashing reason.
Try to update flutter_local_notifications to 9.9.1.

**Comment by rbarzel** [comment]
Working for me now. Thanks!

**Comment by Bunny1376** [comment]
Hi, I face same problem! if I want to use permission_handler package will be okay, but if I use flutter_contacts request permission itself will cause error and crash for the first time ( in both debug and release mode) second run will be okay
